"""adds Spell model

Revision ID: 07352c431b04
Revises: 
Create Date: 2022-05-06 20:07:06.101485

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07352c431b04'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('spell',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('spell')
    # ### end Alembic commands ###
